/**
 * Appends brand symbols to `public/assets/icons.svg` from simple-icons (CC0-1.0)
 * and refreshes the Brotli copy that `vite.config.js` serves under the canonical
 * `icons.svg` URL.
 *
 * Idempotent: symbols already present in the sprite are left untouched, so this
 * can be re-run after adding services. Services with no accurate icon available
 * are intentionally absent — their cards fall back to initials rather than
 * borrowing another brand's mark.
 *
 *   node scripts/generate-icons.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { brotliCompressSync, constants } from 'node:zlib';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as simpleIcons from 'simple-icons';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const spritePath = resolve(root, 'public/assets/icons.svg');
const tonesPath = resolve(root, 'src/data/iconTones.js');

/**
 * Symbols whose tone cannot be read off a single `fill` on the symbol element,
 * because the colour sits on nested paths. Raster and multi-colour symbols are
 * deliberately absent: a raster already carries the white-background filter and
 * would conflict, and one tone cannot describe a multi-colour mark.
 */
const TONE_OVERRIDES = {
  'multiall-aol': 'dark',
  'aiforall-grok': 'dark',
  // Readable (#636466) but a mid grey reads poorly on the dark shell, so it is
  // lightened rather than left at roughly 3.6:1.
  'multiall-wikipedia': 'dark'
};

/** WCAG relative luminance of a #rrggbb colour. */
function luminance(hex) {
  const channels = [0, 2, 4].map((offset) => {
    const value = parseInt(hex.slice(offset, offset + 2), 16) / 255;
    return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
}

/**
 * Flags symbols that would disappear against one of the two icon backdrops:
 * near-black marks on the dark theme's black shell, and near-white or very
 * bright ones on the light theme's white shell.
 *
 * Thresholds come from contrast ratio against those shells: below ~0.05
 * luminance a mark has under 2:1 against black, and above ~0.6 it has under
 * 2:1 against white. Symbols in between are left alone so brands keep their
 * own colour, and multi-fill symbols (no single `fill` on the symbol) are
 * skipped since one value cannot describe them.
 */
function buildTones(svg) {
  const tones = new Map();
  for (const [, id, hex] of svg.matchAll(/<symbol id="([^"]+)"[^>]*\sfill="#([0-9a-fA-F]{6})"/g)) {
    const light = luminance(hex.toLowerCase());
    if (light < 0.05) tones.set(id, 'dark');
    else if (light > 0.6) tones.set(id, 'light');
  }
  for (const [id, tone] of Object.entries(TONE_OVERRIDES)) tones.set(id, tone);
  const entries = [...tones].map(([id, tone]) => `  '${id}': '${tone}',`);
  return [
    '// Generated by scripts/generate-icons.mjs — do not edit by hand.',
    '//',
    "// 'dark'  = the mark is near-black, so it needs lightening on the dark theme.",
    "// 'light' = the mark is near-white or very bright, so it needs darkening on",
    '//           the light theme. Everything else keeps its brand colour as-is.',
    'export const iconTones = {',
    ...entries,
    '};',
    ''
  ].join('\n');
}

/** simple-icons slug per sprite symbol id (without the `multiall-` prefix). */
const SYMBOLS = {
  baidu: 'baidu',
  naver: 'naver',
  searxng: 'searxng',
  unsplash: 'unsplash',
  pexels: 'pexels',
  'google-maps': 'googlemaps',
  'google-images': 'google',
  openstreetmap: 'openstreetmap',
  internetarchive: 'internetarchive',
  arxiv: 'arxiv',
  pubmed: 'pubmed',
  semanticscholar: 'semanticscholar',
  mdn: 'mdnwebdocs',
  npm: 'npm',
  pypi: 'pypi',
  crates: 'rust',
  docker: 'docker',
  archlinux: 'archlinux',
  huggingface: 'huggingface',
  imdb: 'imdb',
  letterboxd: 'letterboxd',
  myanimelist: 'myanimelist',
  anilist: 'anilist',
  spotify: 'spotify',
  soundcloud: 'soundcloud',
  bandcamp: 'bandcamp',
  genius: 'genius',
  goodreads: 'goodreads',
  ebay: 'ebay',
  aliexpress: 'aliexpress',
  etsy: 'etsy',
  'google-news': 'googlenews',
  wikidata: 'wikidata',
  wikimediacommons: 'wikimediacommons',
  wikibooks: 'wikibooks',
  researchgate: 'researchgate',
  ieee: 'ieee',
  zenodo: 'zenodo',
  codeberg: 'codeberg',
  bitbucket: 'bitbucket',
  sourceforge: 'sourceforge',
  packagist: 'packagist',
  rubygems: 'rubygems',
  nuget: 'nuget',
  maven: 'apachemaven',
  go: 'go',
  homebrew: 'homebrew',
  flathub: 'flathub',
  snapcraft: 'snapcraft',
  nixos: 'nixos',
  debian: 'debian',
  ubuntu: 'ubuntu',
  codesandbox: 'codesandbox',
  kaggle: 'kaggle',
  paperswithcode: 'paperswithcode',
  producthunt: 'producthunt',
  devto: 'devdotto',
  hashnode: 'hashnode',
  substack: 'substack',
  threads: 'threads',
  bluesky: 'bluesky',
  lemmy: 'lemmy',
  steam: 'steam',
  gog: 'gogdotcom',
  itchio: 'itchdotio',
  pcgamingwiki: 'pcgamingwiki',
  kick: 'kick',
  odysee: 'odysee',
  peertube: 'peertube',
  dailymotion: 'dailymotion',
  bilibili: 'bilibili',
  rottentomatoes: 'rottentomatoes',
  metacritic: 'metacritic',
  tmdb: 'themoviedatabase',
  lastfm: 'lastdotfm',
  discogs: 'discogs',
  musicbrainz: 'musicbrainz',
  deezer: 'deezer',
  tidal: 'tidal',
  applemusic: 'applemusic',
  youtubemusic: 'youtubemusic',
  yelp: 'yelp',
  tripadvisor: 'tripadvisor',
  airbnb: 'airbnb',
  indeed: 'indeed',
  glassdoor: 'glassdoor',
  coursera: 'coursera',
  edx: 'edx',
  udemy: 'udemy',
  khanacademy: 'khanacademy',
  quizlet: 'quizlet',
  openverse: 'openverse',
'ao3': 'archiveofourown',
  'dblp': 'dblp',
  'orcid': 'orcid',
  'readthedocs': 'readthedocs',
  'freecodecamp': 'freecodecamp',
  'leetcode': 'leetcode',
  'hackerrank': 'hackerrank',
  'codewars': 'codewars',
  'exercism': 'exercism',
  'codeforces': 'codeforces',
  'terraform': 'terraform',
  'ansible': 'ansible',
  'artifacthub': 'artifacthub',
  'kubernetes': 'kubernetes',
  'anaconda': 'anaconda',
  'cran': 'r',
  'haskell': 'haskell',
  'lua': 'lua',
  'perl': 'perl',
  'swift': 'swift',
  'cocoapods': 'cocoapods',
  'gradle': 'gradle',
  'jetbrains': 'jetbrains',
  'chrome': 'googlechrome',
  'firefox': 'firefoxbrowser',
  'wordpress': 'wordpress',
  'postman': 'postman',
  'observable': 'observable',
  'glitch': 'glitch',
  'figma': 'figma',
  'dribbble': 'dribbble',
  'behance': 'behance',
  'artstation': 'artstation',
  'google-fonts': 'googlefonts',
  'fontawesome': 'fontawesome',
  'iconify': 'iconify',
  'simpleicons': 'simpleicons',
  'pixabay': 'pixabay',
  'giphy': 'giphy',
  'tiktok': 'tiktok',
  'rumble': 'rumble',
  'vk': 'vk',
  'zhihu': 'zhihu',
  'lobsters': 'lobsters',
  'newegg': 'newegg',
  'alibaba': 'alibabadotcom',
  'booking': 'bookingdotcom',
  'alltrails': 'alltrails',
  'untappd': 'untappd',
  'deepl': 'deepl',
  'nounproject': 'nounproject',
  'tradingview': 'tradingview',
'wikivoyage': 'wikivoyage',
  'wikisource': 'wikisource',
  'wikiversity': 'wikiversity',
  'fandom': 'fandom',
  'nasa': 'nasa',
  'gitea': 'gitea',
  'launchpad': 'launchpad',
  'yarn': 'yarn',
  'deno': 'deno',
  'jsr': 'jsr',
  'jsdelivr': 'jsdelivr',
  'librariesio': 'librariesdotio',
  'snyk': 'snyk',
  'grafana': 'grafana',
  'docsrs': 'docsdotrs',
  'python': 'python',
  'postgresql': 'postgresql',
  'digitalocean': 'digitalocean',
  'trakt': 'trakt',
  'kitsu': 'kitsu',
  'beatport': 'beatport',
  'mixcloud': 'mixcloud',
  'audiomack': 'audiomack',
  'songkick': 'songkick',
  'applepodcasts': 'applepodcasts',
  'audible': 'audible',
  'px500': '500px',
  'ikea': 'ikea',
  'zara': 'zara',
  'nike': 'nike',
  'adidas': 'adidas',
  'vinted': 'vinted',
  'gumtree': 'gumtree',
  'foursquare': 'foursquare',
  'deliveroo': 'deliveroo',
  'upwork': 'upwork',
  'fiverr': 'fiverr',
  'freelancer': 'freelancer',
  'codecademy': 'codecademy',
  'pluralsight': 'pluralsight',
  'skillshare': 'skillshare',
  'datacamp': 'datacamp',
  'minds': 'minds',
  'allegro': 'allegro',
  'carrefour': 'carrefour',
  'crunchyroll': 'crunchyroll',
  'fnac': 'fnac',
  'mediamarkt': 'mediamarkt',
  'netflix': 'netflix',
  'otto': 'otto',
  'plex': 'plex',
  'rakuten': 'rakuten',
  'taobao': 'taobao',
};

const iconFor = (slug) => simpleIcons[`si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`];
const escapeXml = (value) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

let sprite = readFileSync(spritePath, 'utf8');
const added = [];
const missing = [];
const symbols = [];

for (const [id, slug] of Object.entries(SYMBOLS)) {
  const symbolId = `multiall-${id}`;
  if (sprite.includes(`id="${symbolId}"`)) continue;

  const icon = iconFor(slug);
  if (!icon) {
    missing.push(`${symbolId} (no simple-icons entry for "${slug}")`);
    continue;
  }

  symbols.push(
    `  <symbol id="${symbolId}" viewBox="0 0 24 24" fill="#${icon.hex}">` +
    `<title>${escapeXml(icon.title)}</title><path d="${icon.path}" /></symbol>`
  );
  added.push(symbolId);
}

if (symbols.length) {
  const closing = sprite.lastIndexOf('</svg>');
  sprite = `${sprite.slice(0, closing)}${symbols.join('\n')}\n${sprite.slice(closing)}`;
  writeFileSync(spritePath, sprite);
}

// Keep the precompressed copy in step, or production would serve a stale sprite.
writeFileSync(
  `${spritePath}.br`,
  brotliCompressSync(readFileSync(spritePath), {
    params: { [constants.BROTLI_PARAM_QUALITY]: 11 }
  })
);

writeFileSync(tonesPath, buildTones(sprite));


const total = (sprite.match(/<symbol /g) ?? []).length;
console.log(`added ${added.length} symbol(s); sprite now has ${total}`);
if (added.length) console.log(added.join(', '));
if (missing.length) console.log(`skipped:\n${missing.join('\n')}`);
